// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanItem } from "./PlanItem";

export type CleanupPlan = { session_id: string, target_bytes: string | null, selected_candidate_bytes: string, selected_review_bytes: string, review_potential_bytes: string, target_shortfall_bytes: string, items: Array<PlanItem>, };
