// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DismissSuggestionRequest = { node_id: string, rule_id: string, dismissed: boolean, };
