// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";
import type { OwnerSummary } from "./OwnerSummary";
import type { PolicyEvidence } from "./PolicyEvidence";

export type ItemRow = { id: string, parent_id: string | null, name: string, display_path: string, kind: ItemKind, logical_bytes: string, allocated_bytes: string, modified_at_ms: string | null, extension: string | null, attributes: Array<string>, hard_link_count: number | null, child_count: number | null, owner: OwnerSummary | null, policy: PolicyEvidence, };
