// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";
import type { ItemSort } from "./ItemSort";
import type { PolicyTier } from "./PolicyTier";
import type { SortDirection } from "./SortDirection";

export type ItemQuery = { parent_id: string | null, recursive: boolean, top_only?: boolean, scope_id?: string, text?: string, kinds?: Array<ItemKind>, extensions?: Array<string>, policy_tiers?: Array<PolicyTier>, owner_ids?: Array<string>, min_bytes?: string, modified_before_ms?: string, query_id?: string, sort: ItemSort, direction: SortDirection, cursor: string | null, limit: number, };
