// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemRow } from "./ItemRow";
import type { PolicyEvidence } from "./PolicyEvidence";

export type ItemDetails = { item: ItemRow, evidence: PolicyEvidence, };
