// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LogExcerpt = { item_id: string, display_path: string, encoding: string, content: string, original_bytes: string, returned_bytes: string, truncated: boolean, };
