// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogExcerpt } from "./LogExcerpt";

export type LogExcerptBatch = { excerpts: Array<LogExcerpt>, total_returned_bytes: string, };
