// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OwnerMatchKind } from "./OwnerMatchKind";
import type { OwnerSource } from "./OwnerSource";

export type OwnerSummary = { id: string, name: string, source: OwnerSource, match_kind: OwnerMatchKind, };
