// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanActionKind } from "./PlanActionKind";
import type { PolicyEvidence } from "./PolicyEvidence";
import type { PolicyTier } from "./PolicyTier";

export type PlanItem = { id: string, node_ids: Array<string>, title: string, category: string, tier: PolicyTier, selected: boolean, reclaimable_bytes: string, evidence: Array<PolicyEvidence>, warnings: Array<string>, action_kind: PlanActionKind, };
