// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanActionKind = "inspect" | "open_location" | "open_windows_apps_settings" | "open_windows_storage_settings" | "run_ollama_rm" | "run_scoop_cleanup" | "run_scoop_cache" | "none";
