// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyTier } from "./PolicyTier";

export type PolicyEvidence = { tier: PolicyTier, rule_id: string, rule_version: string, facts: Array<string>, inference: Array<string>, warnings: Array<string>, };
