// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanTargetKind } from "./ScanTargetKind";

export type ScanTarget = { id: string, kind: ScanTargetKind, display_path: string, filesystem: string | null, volume_id: string | null, total_bytes: string | null, available_bytes: string | null, fast_scan_available: boolean, };
