// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanBackend } from "./ScanBackend";
import type { ScanCoverage } from "./ScanCoverage";
import type { ScanTarget } from "./ScanTarget";
import type { ScanWarning } from "./ScanWarning";

export type ScanSummary = { session_id: string, target: ScanTarget, backend: ScanBackend, coverage: ScanCoverage, entry_count: string, logical_bytes: string, allocated_bytes: string, volume_used_bytes: string | null, unaccounted_bytes: string | null, started_at_ms: string, completed_at_ms: string, elapsed_ms: string, warnings: Array<ScanWarning>, };
