// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanBackend } from "./ScanBackend";
import type { ScanPhase } from "./ScanPhase";
import type { ScanWarning } from "./ScanWarning";

export type ScanProgress = { session_id: string, phase: ScanPhase, backend: ScanBackend, entries_seen: string, bytes_accounted: string, elapsed_ms: string, warnings: Array<ScanWarning>, };
