// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanBackend } from "./ScanBackend";
import type { ScanTarget } from "./ScanTarget";

export type ScanRequest = { target: ScanTarget, preferred_backend: ScanBackend, };
