// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregateDimension } from "./AggregateDimension";

export type StorageAggregateQuery = { scope_id: string | null, dimension: AggregateDimension, limit: number, };
