// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBucket } from "./StorageBucket";

export type StorageAggregate = { buckets: Array<StorageBucket>, other_item_count: string, other_logical_bytes: string, other_allocated_bytes: string, };
