// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreemapNode } from "./TreemapNode";

export type TreemapSlice = { nodes: Array<TreemapNode>, truncated: boolean, other_allocated_bytes: string, };
