// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemKind } from "./ItemKind";
import type { PolicyTier } from "./PolicyTier";

export type TreemapNode = { id: string, parent_id: string | null, name: string, allocated_bytes: string, kind: ItemKind, policy_tier: PolicyTier, owner_id: string | null, synthetic: boolean, };
